Config = {}

Config.NewCore = true

Config.GaragePed = "s_m_y_xmech_01"

Config.PedLocation = vec4(-597.5389, -1055.6312, 21.3442, 188.6517)

Config.VehicleSpawn = vector4(-596.5880, -1059.0718, 22.1253, 91.0356)

Config.Vehicle = 'nspeedo'

HungerFill = { -- How much they fill your hunger
    ["gingerkitty_cookie"] = math.random(35, 45),
    ["kira_kira_currye"] = math.random(35, 45),
    ["om_nom_omurice"] = math.random(35, 45),
    ["dragos_fire_cupcake"] = math.random(35, 45),
    ["ballbarry_cupcake"] = math.random(35, 45),
    ["purrfect_parfait"] = math.random(35, 45),
    ["oxygen_cake"] = math.random(35, 45),
    ["meowchi_mochi_ice_cream"] = math.random(35, 45),
    ["strawberry_shortcake"] = math.random(35, 45),
    ["awwdorable_valentines_chocolate"] = math.random(35, 45),
    ["warm_chicken_noodle"] = math.random(35, 45),
    ["rice_balls"] = math.random(35, 45),
    ["doki_doki_pancakes"] = math.random(35, 45),
    ["hamburg_stake"] = math.random(35, 45),
    ["sugoi_katsu_sando"] = math.random(35, 45),
    ["cat_macaroon_pink"] = math.random(35, 45),
    ["cat_macaroon_green"] = math.random(35, 45),
    ["cat_macaroon_turquoise"] = math.random(35, 45),
    ["cat_macaroon_brown"] = math.random(35, 45),
}

ThirstFill = { -- How much they fill your thirst.
    ["sweet_herbal_tea"] = math.random(25, 35),
    ["booba_milk_tea_2"] = math.random(25, 35),
    ["lovely_hot_chocolate"] = math.random(25, 35),
    ["hot_chocolate"] = math.random(25, 35),
    ["matcha_coffee"] = math.random(25, 35),
}

Config.Zones = {
    [1] = { coords = vector3(-584.17, -1062.07, 22.4), radius = 0.35, icon = "fa-solid fa-hand-holding", event = "nmsh-uwucafe:client:tray1", label = "Tray", },
    [2] = { coords = vector3(-584.04, -1059.31, 22.4), radius = 0.35, icon = "fa-solid fa-hand-holding", event = "nmsh-uwucafe:client:tray2", label = "Tray", },
    [3] = { coords = vector3(-586.57, -1062.95, 22.4), radius = 0.35, icon = "fa-solid fa-hand-holding", event = "nmsh-uwucafe:client:tray3", label = "Tray", },
    [4] = { coords = vector3(-587.99, -1058.07, 21.89), radius = 0.5, icon = "fa-solid fa-warehouse", event = "nmsh-uwucafe:client:stash1", label = "Stash", job = "uwu" }, 
    [5] = { coords = vector3(-587.79, -1060.18, 21.81), radius = 0.5, icon = "fa-solid fa-warehouse", event = "nmsh-uwucafe:client:stash2", label = "Stash", job = "uwu" }, 
    [6] = { coords = vector3(-587.41, -1059.71, 22.53), radius = 0.7, icon = "fa-solid fa-warehouse", event = "nmsh-uwucafe:client:stash3", label = "Stash", job = "uwu" }, 
    [7] = { coords = vector3(-585.25, -1055.29, 22.34), radius = 0.78, icon = "fa-solid fa-warehouse", event = "nmsh-uwucafe:client:stash4", label = "Stash", job = "uwu" }, 
    [8] = { coords = vector3(-588.02, -1066.11, 22.34), radius = 0.8, icon = "fa-solid fa-warehouse", event = "nmsh-uwucafe:client:stash5", label = "Stash", job = "uwu" }, 
    [9] = { coords = vector3(-588.03, -1067.97, 22.34), radius = 0.8, icon = "fa-solid fa-warehouse", event = "nmsh-uwucafe:client:stash6", label = "Stash", job = "uwu" }, 
    [10] = { coords = vector3(-590.6, -1068.04, 22.34), radius = 0.8, icon = "fa-solid fa-warehouse", event = "nmsh-uwucafe:client:stash7", label = "Stash", job = "uwu" }, 
    [11] = { coords = vector3(-598.38, -1062.47, 22.99), radius = 1.55, icon = "fa-solid fa-warehouse", event = "nmsh-uwucafe:client:stash8", label = "Stash", job = "uwu" }, 
    [12] = { coords = vector3(-597.69, -1065.61, 22.99), radius = 1.55, icon = "fa-solid fa-warehouse", event = "nmsh-uwucafe:client:stash9", label = "Stash", job = "uwu" }, 
    [13] = { coords = vector3(-598.06, -1068.31, 22.99), radius = 1.55, icon = "fa-solid fa-warehouse", event = "nmsh-uwucafe:client:stash10", label = "Stash", job = "uwu" }, 
    [14] = { coords = vector3(-590.89, -1058.66, 22.62), radius = 0.7, icon = "fa-solid fa-ice-cream", event = "nmsh-uwucafe:client:refregiator", label = "Refregiator", job = "uwu" }, 
    [15] = { coords = vector3(-591.03, -1063.05, 22.36), radius = 0.5, icon = "fa-solid fa-muh-hot", event = "nmsh-uwucafe:client:makeSides", label = "Sides", job = "uwu" },
    [17] = { coords = vector3(-590.95, -1064.1, 22.49), radius = 0.36, icon = "fa-solid fa-mug-hot", event = "nmsh-uwucafe:client:makeDeserts", label = "Deserts", job = "uwu" },
    [18] = { coords = vector3(-590.6, -1059.81, 22.65), radius = 0.36, icon = "fa-solid fa-fire-burner", event = "nmsh-uwucafe:client:useOven", label = "Oven", job = "uwu" },
    [19] = { coords = vector3(-587.96, -1062.59, 22.34), radius = 0.45, icon = "fa-solid fa-sink", event = "nmsh-uwucafe:client:useSink", label = "Sink", job = "uwu" },
    [20] = { coords = vector3(-591.07, -1056.52, 22.38), radius = 0.44, icon = "fa-solid fa-bowl-food", event = "nmsh-uwucafe:client:makeFood", label = "Food", job = "uwu" },
    [21] = { coords = vector3(-583.98, -1058.18, 22.74), radius = 0.5, icon = "fa-solid fa-mug-hot", event = "nmsh-uwucafe:client:makeTea", label = "Tea", job = "uwu" },
    [22] = { coords = vector3(-586.74, -1061.95, 22.64), radius = 0.4, icon = "fa-solid fa-mug-saucer", event = "nmsh-uwucafe:client:makeCoffee", label = "Coffee Machine", job = "uwu" },
    [23] = { coords = vector3(-577.7687, -1066.8713, 26.5152), radius = 0.7, icon = "fa-solid fa-building", event = "nmsh-bossmenu:client:OpenMenu", label = "Boss Menu", job = {['uwu'] = 4} },
    [24] = { coords = vector3(-706.06, -913.97, 19.22), radius = 0.8, icon = "fa-solid fa-basket-shopping", event = "nmsh-uwucafe:client:openShop", label = "UwU Shop", job = "uwu" },
    [25] = { coords = vector3(-589.35, -1068.52, 21.84), radius = 0.7, icon = "fa-solid fa-boxes-stacked", event = "nmsh-uwucafe:client:grabIce", label = "Ice Machine", job = "uwu" },
    [26] = { coords = vector3(-594.35, -1054.15, 23.04), radius = 0.6, icon = "fa-solid fa-martini-glass-citrus", event = "nmsh-uwucafe:clientToggleDuty", label = "Toggle Duty", job = "uwu" },
    [27] = { coords = vector3(-584.03, -1061.47, 22.34), radius = 0.25, icon = "fa-solid fa-cash-register", event = "nmsh-uwucafe:bill", label = "Cash Register", job = "uwu" },
    [28] = { coords = vector3(-583.99, -1058.74, 22.34), radius = 0.25, icon = "fa-solid fa-cash-register", event = "nmsh-uwucafe:bill", label = "Cash Register", job = "uwu" },
}

Config.Items = {
label = "UwU Cafe Shop",
    slots = 37,
    items = {
        [1] = {
            name = "glass_tall_dirty",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "butter",
            price = 2,
            amount = 2,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "cup_dirty",
            price = 8,
            amount = 20,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "cocoa_powder",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "dried_boba_tapioca_pearls",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "egg",
            price = 8,
            amount = 1,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "flour",
            price = 8,
            amount = 1,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "chicken",
            price = 8,
            amount = 8,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "chicken_breast",
            price = 4,
            amount = 20,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "chicken_thighs",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "jelly_beans",
            price = 1,
            amount = 20,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "juice",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "lemon",
            price = 1,
            amount = 20,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "matcha_powder",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "milk",
            price = 1,
            amount = 20,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "nuts",
            price = 1,
            amount = 20,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "onion",
            price = 1,
            amount = 20,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "pullman_bread",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "rice_flour",
            price = 3,
            amount = 20,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "rice",
            price = 1,
            amount = 20,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "sea_moss",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "soy_sauce",
            price = 6,
            amount = 20,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "strawberry",
            price = 1,
            amount = 20,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "sugar",
            price = 1,
            amount = 20,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "uwu_mysterybox",
            price = 10,
            amount = 20,
            info = {},
            type = "item",
            slot = 25,
        },
        [26] = {
            name = "baking_powder",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 26,
        },
        [27] = {
            name = "virgin_olive_oil",
            price = 10,
            amount = 20,
            info = {},
            type = "item",
            slot = 27,
        },
        [28] = {
            name = "noodles",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 28,
        },
        [29] = {
            name = "mint",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 29,
        },
        [30] = {
            name = "brewed_coffee",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 30,
        },
        [31] = {
            name = "steak",
            price = 15,
            amount = 20,
            info = {},
            type = "item",
            slot = 31,
        },
        [32] = {
            name = "brown_dye",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 32,
        },
        [33] = {
            name = "pink_dye",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 33,
        },
        [34] = {
            name = "green_dye",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 34,
        },
        [35] = {
            name = "turquoise_dye",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 35,
        },
        [36] = {
            name = "plate_dirty",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 36,
        },
        [37] = {
            name = "bar_bowl_dirty",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 37,
        },
    }
}
